### ISSUE TITLE
Failed to Boot Pi3

### ISSUE THREAD

**Issue by samvenson** [resin-io-playground/resin-wpe#3]
starting application results in the following message:

 Starting application 'registry2.resin.io/wpespial/70eeb14b8ff2512a3d2c018c158c34ddc7aa65cd'
15.05.17 10:43:40 (-0400) Started application 'registry2.resin.io/wpespial/70eeb14b8ff2512a3d2c018c158c34ddc7aa65cd'
15.05.17 10:43:41 (-0400) [LibinputServer] Initialization of linux input system succeeded.
15.05.17 10:43:41 (-0400) [LibinputServer] Enabling handle events.
15.05.17 10:43:41 (-0400) * failed to add service - already in use?

No HDMI signal detected.
Tries forcing it - no game.

**Comment by markov00** [comment]
old issue by I've just found the same problem and solved with setting up the device config on resin.io with one of the following parameters `RESIN_HOST_CONFIG_gpu_mem_`

**Comment by petrosagg** [comment]
@markov00 thanks for figuring it out
