### ISSUE TITLE
Question with touch scrolling

### ISSUE THREAD

**Issue by markbarton** [resin-io-playground/resin-wpe#4]
I am using a 7 inch Pi touchscreen - the official one I think - https://thepihut.com/products/official-raspberry-pi-7-touchscreen-display?variant=4916536388 and it works fine.

I adjusted the screen resolution using RESIN_HOST_CONFIG_hdmi_cvt	800 480 60 1 0 0 0 and set the GPU environment variables and it displays fine.

Touch click works but I can't scroll using my finger - is it not supported?  Or am I missing a environment variable?

Thanks

Mark

**Comment by petrosagg** [comment]
I don't think touch scroll is supported because this is something usually handled by the window manager. Webkit just renders a page and forwards touch events to the web page so I guess you'll have to handle scrolling in JS itself. Closing the issue but feel free to ask any more questions
