### ISSUE TITLE
Keyboard doesn't work fully

### ISSUE THREAD

**Issue by dirkmoors** [resin-io-playground/resin-wpe#5]
Hello,

It seems that my keyboard does not work completely under WPE:

Only alphanumerical characters [a-zA-Z0-9] seem to work. For instance, I cannot get '@' to show up...

Any clue as to what I might be doing wrong here?

Best regards

**Comment by petrosagg** [comment]
I reproduced this issue but I'm not sure why it's caused. It might have to do with the integration of libinput and wpewebkit.

**Comment by csmjulian** [comment]
@petrosagg Have you made any progress with fixing this? If not, could you point me in the right direction to learn how to adjust my image during the Yocto build process?

**Comment by petrosagg** [comment]
@csmjulian I haven't made any progress. What kind of adjustments are you talking about?

**Comment by csmjulian** [comment]
@petrosagg Well you mentioned earlier that this issue could be related to the integration of libinput and wpewebkit. I was wondering what could be done to help such as making adjustments in the image configuration and rebuilding.

**Comment by petrosagg** [comment]
The issue will most likely be further upstream and not in the yocto build of this repo. The keyboard integration of libinput with WPE is done here https://github.com/WebPlatformForEmbedded/WPEBackend-rdk/blob/master/src/input/Libinput/LibinputServer.cpp#L202-L222

What I'd do is add some logging there to see what's going on. It looks like Shift and modifiers in general are not handled?

**Comment by petrosagg** [comment]
There seems to be some modifier handling code here https://github.com/WebPlatformForEmbedded/WPEBackend-rdk/blob/master/src/input/LinuxInput/KeyboardEventHandlerLinuxInput.cpp#L152-L164

It is behind the `KEY_INPUT_HANDLING_LINUX_INPUT`, so one experiment is to check if this is enabled and working correctly

**Comment by petrosagg** [comment]
@csmjulian this should be fixed now. I also PRed it upstream, you can track it here https://github.com/WebPlatformForEmbedded/WPEBackend-rdk/pull/16
