### ISSUE TITLE
GStreamer-CRITICAL Error with youtube live video 

### ISSUE THREAD

**Issue by samouds** [resin-io-playground/resin-wpe#7]
Hello,

I test the resin-wpe with a live video from youtube 👍 

WPE_URL = https://www.youtube.com/embed/hL0sEdVJs3U?autoplay=1&vq=hd720

But the video won't start and I get this error :

```
(WPEWebProcess:39): GStreamer-CRITICAL **: _gst_util_uint64_scale: assertion 'denom != 0' failed
```

Any idea ?

Thanks.

**Comment by sqweelygig** [comment]
From https://forums.resin.io/t/resin-wpe-gstreamer-critical-error-with-youtube-live-video/2171/4

**Comment by samouds** [comment]
Hello,

I get this response from WPEWebKit team : https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/411#issuecomment-346425899

> You need a patched GStreamer to solve this issue. It's solved in WebKit upstream here:
https://bugs.webkit.org/show_bug.cgi?id=176804
I've just backported the patch to gst1-plugins-good in buildroot here:
WebPlatformForEmbedded/buildroot@85e8095

**Comment by petrosagg** [comment]
@samouds I updated WPE to the latest version that includes the fix for this problem. I tested with the link you provided and it seems to be working. Feel free to re-open if you still experience issues

**Comment by samouds** [comment]
Thanks @petrosagg I get this fixed this morning too :) and checked with a live stream from youtube and it's working perfectly !

Big thanks to the resin team and to you.
