### ISSUE TITLE
Automatic Page Refresh

### ISSUE THREAD

**Issue by alexanderpreston** [resin-io-playground/resin-wpe#8]
What would be the easiest way of implementing an automatic page refresh? For instance, every 10 minutes, for pages that don't automatically refresh their own data.

**Comment by petrosagg** [comment]
I think the easiest is using a wrapping page with an `iframe` and some js to recreate it every 10 minutes. Otherwise you can restart the browser by modifying the init script

**Comment by alexanderpreston** [comment]
Thanks for the response Petros.

Is it feasible to use either of those two approaches whilst simultaneously allowing an environment variable to be set to control the duration of the refresh interval via the resin.io interface?

Alex.


Alexander Preston
Managing Director
Intrepid
e: alexander@beintrepid.co.uk
t: +442037276351
m: +447414829862
85 Tottenham Court Road
London
W1T 4TQ
We believe technology should provide us with more of our most precious resource, time.
Information Technology | Software Development | Process Engineering
Disclaimer:
This message contains confidential information for the intended recipient only. If you are not the intended recipient you should not disseminate, distribute or copy this e-mail. Please notify immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Intrepid Ltd therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.
Intrepid Ltd is a company registered in England and Wales under number 07480378. Registered office: 28 Newell Road, Hemel Hempstead, Hertfordshire, HP3 9PB, UK.

**Comment by petrosagg** [comment]
Yes, you can write a for loop or create a JS file that has the variable for the iframe option. `echo "var TIMEOUT = ${TIMEOUT};" > config.js`

**Comment by alexanderpreston** [comment]
If I am serving a remote page (where I don’t have control over the source) is wrapping it in an iframe the only option here?


Alexander Preston
Managing Director
Intrepid
e: alexander@beintrepid.co.uk
t: +442037276351
m: +447414829862
85 Tottenham Court Road
London
W1T 4TQ
We believe technology should provide us with more of our most precious resource, time.
Information Technology | Software Development | Process Engineering
Disclaimer:
This message contains confidential information for the intended recipient only. If you are not the intended recipient you should not disseminate, distribute or copy this e-mail. Please notify immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Intrepid Ltd therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.
Intrepid Ltd is a company registered in England and Wales under number 07480378. Registered office: 28 Newell Road, Hemel Hempstead, Hertfordshire, HP3 9PB, UK.

**Comment by petrosagg** [comment]
No, you can also kill the browser and bring it back up at the interval you want. Not exactly a refresh though
